### ISSUE TITLE
Issue Getting Results from show running-config

### ISSUE THREAD

**Issue by jessebarton** [shenbowei/switch-ssh-go#2]
`cmds := make([]string, 0)
	cmds = append(cmds, "show running-config")
	// cmds = append(cmds, "show run")
	result, err := ssh.RunCommandsWithBrand(user, password, ipPort, ssh.CISCO, cmds...)
	if err != nil {
		fmt.Println("RunCommands err:\n", err.Error())
	}
	// time.Sleep(5)
	fmt.Println("RunCommands result:\n", result)
	file, err := os.Create("output.txt")
	if err != nil {
		log.Fatalln(err, file)

	}
	i, err := file.WriteString(result)
	if err != nil {
		log.Fatalln(err, i)

	}
	fmt.Printf("%d", i)`

result is 

`show running-config
Building configuration...`

no output from this command comes through. Any idea why this would happen?

**Comment by shenbowei** [comment]
sorry, I don't have a Cisco switch on hand.
I think it might be a timeout, you could try to increase the delay time.
[https://github.com/shenbowei/switch-ssh-go/blob/master/ssh.go#L54](url)
Thank you for your feedback.
