### ISSUE TITLE
大家遇到了没有

### ISSUE THREAD

**Issue by yanhao1** [shenbowei/switch-ssh-go#5]
[ERROR]:SSH Dial err:ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group1-sha1 diffie-hellman-group-exchange-sha1]

**Comment by shenbowei** [comment]
https://github.com/shenbowei/switch-ssh-go/blob/master/ssh_session.go#L83
在上述代码后增加：
```
KeyExchanges: []string{"diffie-hellman-group-exchange-sha1"},
```
看看能不能解决你的问题

**Comment by toujourser** [comment]
ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group1-sha1]

大佬, 我遇到个问题提示上面错误信息, 如何解决

**Comment by yanhao1** [comment]
> ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [[curve25519-sha256@libssh.org](mailto:curve25519-sha256@libssh.org) ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group1-sha1]
> 
> 大佬, 我遇到个问题提示上面错误信息, 如何解决

我也碰到这样的问题，没有解决，网上方法都不行 ，修改ssh配置解决不了，不兼容ssh老的加密算法。

**Comment by shenbowei** [comment]
增加KeyExchanges配置项还是不行吗？我现在没有交换机设备可以测试……

**Comment by toujourser** [comment]
> 增加KeyExchanges配置项还是不行吗？我现在没有交换机设备可以测试……

不行, 网上的很多方法都试过了还是不行

**Comment by jiangdequan** [comment]
> https://github.com/shenbowei/switch-ssh-go/blob/master/ssh_session.go#L83
> 在上述代码后增加：
> 
> ```
> KeyExchanges: []string{"diffie-hellman-group-exchange-sha1"},
> ```
> 
> 看看能不能解决你的问题

我这边遇到这个问题了，添加了可以解决问题

**Comment by Forward-Ky** [comment]
> https://github.com/shenbowei/switch-ssh-go/blob/master/ssh_session.go#L83
> 在上述代码后增加：
> 
> ```
> KeyExchanges: []string{"diffie-hellman-group-exchange-sha1"},
> ```
> 
> 看看能不能解决你的问题
https://github.com/shenbowei/switch-ssh-go/blob/master/ssh_session.go#L83
在上述代码后增加：
`KeyExchanges: []string{"curve25519-sha256@libssh.org", "ecdh-sha2-nistp256", "ececdh-sha2-nistp384", "ecdh-sha2-nistp521", "diffie-hellman-group14-sha1", "diffie-hellman-group1-sha1"},`
解决；
另外 Cisco ASA 的  CiscoNoPage  = "terminal length 0"  是CiscoASANoPage = “terminal pager 0”
