### ISSUE TITLE
连接交换机设备提示这个错误如何解决?

### ISSUE THREAD

**Issue by toujourser** [shenbowei/switch-ssh-go#6]
ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group1-sha1]

**Comment by shenbowei** [comment]
https://github.com/shenbowei/switch-ssh-go/blob/master/ssh_session.go#L83
在上述代码后增加：
```
KeyExchanges: []string{"diffie-hellman-group1-sha1"},
```
这样修改试试，我现在没有交换机可以测试，有结果麻烦留下言，谢谢
